spring: 
 profiles: 
  active: 
   - dev

---
spring: 
 profiles: dev
 application: 
  name: microservice-config-chenwei-dev
---
spring: 
 profiles: test
 application: 
  name: microservice-config-chenwei-test