spring: 
 profiles: 
  active: 
   - dev
---
server:
  port: 8001

mybatis:
 # config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.wei.springcloud.entitys
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: dev
  application:
    name: microservice-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka 单机
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: longjun-microservice
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: ${project.version}
  
---
server:
  port: 8002

mybatis:
 # config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.wei.springcloud.entitys
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: test
  application:
    name: microservice-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud2?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka 单机
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: longjun-microservice
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: ${project.version}